id = "coverage-lsp"
name = "Coverage LSP"
description = "Coverage Language Server Protocol."
version = "0.0.1"
schema_version = 1
authors = ["Sylvain Fargier <fargier.sylvain@gmail.com>"]
repository = "https://FIXME"

[language_servers.coverage-lsp]
name = "CoverageLSP Server"
languages = [
    "HTML",
    "JSON",
    "JSONC",
    "JSON5",
    "Tera",
    "Tera (HTML)",
    "Tera (CSS)",
    "Tera (JSON)",
    "Tera (YAML)",
    "Tera (TOML)",
    "ERB",
    "JavaScript",
    "TypeScript",
    "CSS",
    "JSX",
    "TSX",
    "Vue.js",
    "YAML",
    "TOML",
    "XML",
    "Rust",
    "Ruby",
    "Python",
    "Go",
]
code_action_kinds = []
