id = "coverage-lsp"
name = "Coverage LSP"
description = "Code Coverage Language Server"
version = "1.0.1"
schema_version = 1
authors = ["Sylvain Fargier <fargier.sylvain@gmail.com>"]
repository = "https://github.com/fargies/coverage-lsp"

[language_servers.coverage-lsp]
name = "Coverage LSP Server"
languages = ["C", "C++", "Go", "Rust", "JavaScript", "TypeScript"]
code_action_kinds = []
